services:
  - type: web
    name: lion-group-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
